version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    enviroment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
